steps:
  # Step 1: Build with Maven
  - name: 'maven:3.8.4'
    args: ['mvn', 'clean', 'install']

  # Step 2: Build the Docker Image
  - name: gcr.io/cloud-builders/docker
    args: [
      'build', 
      '-t', 
      'gcr.io/gcb-security-bu/docker-spring-boot-java-web:latest',
      '.'
    ]

  # Step 3: Push the Docker Image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gcb-security-bu/docker-spring-boot-java-web:latest']

  # Step 4: Scan the container image with AccuKnox and save the report
  - name: 'accuknox/accuknox-container-scan'
    args: [
      'image', 
      '--format', 'json', 
      '--output', '/workspace/accuknox-report.json', 
      '${_IMAGE_URL}:${_IMAGE_TAG}',
    ]
    id: 'accuknox-container-scan'

  # Step 5: Upload the AccuKnox report to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '/workspace/accuknox-report.json', 'gs://accuknox-pipeline/accuknox-report.json']
    waitFor: ['accuknox-container-scan']

  # Step 6: Print the AccuKnox container scan results
  - name: 'ubuntu'
    entrypoint: 'cat'
    args: ['/workspace/accuknox-report.json']
    waitFor: ['accuknox-container-scan']

  # Step 7: Forward the logs to the SaaS platform using curl
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'curl --location --request POST "https://${_CSPM_URL}/api/v1/artifact/?tenant_id=${_TENANT_ID}&data_type=TR&save_to_s3=false"  --header "Tenant-Id: 2245" --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0NzE1NzIwLCJqdGkiOiJiNzYxNmQ1NmRiZWU0ZWVhYjdiZjc3NDJhNmJkMzVhMCIsImlzcyI6ImNzcG0uZGVtby5hY2N1a25veC5jb20ifQ.ENT7bvSvqmmxsnopOGN4-_aS9XJgtPLY635d16_Tc2B0MOaHIIZUAocPeSZbRXv174tFtkVhWwBLwjiQT9xWT6R2jYIxGK7PkG4EFW_xDMC3M-VNxOQknriWjs4H_9MO2jvnc7ygf-0CSBYxosn5lwMe2rDWWfi3mA7ZullMKMHsaGStVjVO1Qv7TzpucPdAwR4uq49tBm9NRzXu9vNUxkbsEDzFoxpPHnZ7ytcCziwtI1f3dXoDHmuDhQLJewVqyqpbncLGdXXpJE7dB__gtXlnt4gRetrJWtzbG2aUKl-Gh1KYM1WhnoisHyMy7uw26batq3O7dJTvZGRQPBTrUQ" --form "file=@/workspace/accuknox-report.json"'
      ]
    waitFor: ['accuknox-container-scan']

  # Step 8: If there are critical or high vulnerabilities, stop deployment
  - name: 'bash'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'if grep -q "CRITICAL\|HIGH" /workspace/accuknox-report.json; then  echo "critical or high vulnerabilities found in image"; exit 1; else exit 0; fi'
      ]
    waitFor: ['accuknox-container-scan']

  # Step 9: Apply Kubernetes Configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-gcb-security-bu'
    waitFor: ['accuknox-container-scan']

  # Step 10: Update the Deployment Image
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set', 
      'image', 
      'deployment', 
      'spring-boot-java-web', 
      'spring-boot-java-web=gcr.io/gcb-security-bu/docker-spring-boot-java-web:latest'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-gcb-security-bu'
    waitFor: ['accuknox-container-scan']

# Push the image to Google Container Registry with the latest tag
images: [
   'gcr.io/gcb-security-bu/docker-spring-boot-java-web:latest'
]

# Specify the logs bucket and build timeout
logsBucket: 'gs://accuknox-pipeline'
timeout: '1200s'

# Define substitutions
substitutions:
  _IMAGE_URL: 'gcr.io/gcb-security-bu/docker-spring-boot-java-web'
  _IMAGE_TAG: 'latest'
  _CSPM_URL: 'cspm.demo.accuknox.com'
  _TENANT_ID: '2245'
